### ISSUE TITLE
Submit Projects

### ISSUE THREAD

**Issue by gitsofaryan** [gitsofaryan/Hacktoberfest-Projects-2025#1]

**Comment by Jayesh-Waghmare** [comment]
Hi @gitsofaryan , Could you please assign me this issue? ... Thank you

**Comment by Jayesh-Waghmare** [comment]
Hi @gitsofaryan which tech stack do you want that I need to submit here? Should the projects be basic or intermediate level?

**Comment by gitsofaryan** [comment]
hi @Jayesh-Waghmare you can submit any of your project, this repo is for beginners and open source enthusiasts.
